version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing Maven 3.9.6
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      - tar xzvf apache-maven-3.9.6-bin.tar.gz
      - mv apache-maven-3.9.6 /usr/local/maven
      - ln -s /usr/local/maven/bin/mvn /usr/local/bin/mvn
      - mvn --version
  pre_build:
    commands:
      - echo Initializing environment
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain subrataroy --domain-owner 273348327215 --region us-east-1 --query authorizationToken --output text`

  build:
    commands:
      - echo Runnings Tests
      - mvn -s settings.xml clean test -X
      - echo Build started on `date`
      - mvn -s settings.xml compile
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -s settings.xml package
artifacts:
  files:
    - target/nextwork-7d-devops-project.war
  discard-paths: no
